# Generated by Django 6.0.5 on 2026-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_days',
            field=models.SmallIntegerField(default=0, verbose_name='количество дней'),
        ),
    ]
