# Generated by Django 5.2.8 on 2026-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customauthenticationuser',
            name='roles',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Owner', 'Owner'), ('Default_user', 'Default_user')], default='Default_user', verbose_name='Роли пользователей'),
        ),
    ]
