# Generated by Django 5.2.8 on 2026-05-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
