# Generated by Django 5.2.8 on 2026-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
