# Generated by Django 6.0.5 on 2026-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_place',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество мест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='square',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Жилая площадь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default=1, max_length=128, verbose_name='room_title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hostel_images',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='', verbose_name='Фотошрафии'),
        ),
    ]
