# Generated by Django 5.2.8 on 2026-06-02 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_image_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='min_price',
            field=models.IntegerField(default=0, verbose_name='Минимальная цена за ночь'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания комнаты'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_images', models.ImageField(upload_to='', verbose_name='Фото_блюда')),
                ('title', models.CharField(max_length=256, verbose_name='Название блюда')),
                ('composition', models.TextField(verbose_name='Состав блюда')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес блюда')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='ссылка_на_отель')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_images', models.ImageField(upload_to='', verbose_name='Фото_услуги')),
                ('title', models.CharField(max_length=256, verbose_name='Название услуги')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена усплуги')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Длительность')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='ссылка_отель')),
            ],
        ),
    ]
